# fly.toml app configuration file for northeastern-university-chatbot-broken-pond-9350
# Free tier configuration

app = 'northeastern-university-chatbot-broken-pond-9350'
primary_region = 'bos'

[build]

[env]
  PORT = "8001"

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "python -m uvicorn services.chat_service.api:app --host 0.0.0.0 --port 8001"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1 