[phases.setup]
nixPkgs = ["python39", "gcc", "g++"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn services.chat_service.enhanced_openai_api:app --host 0.0.0.0 --port $PORT"

