services:
  - type: web
    name: northeastern-chatbot-enhanced-gpu
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start_production.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: HOST
        value: 0.0.0.0
      - key: WORKERS
        value: 1
      - key: LOG_LEVEL
        value: info
      - key: OLLAMA_HOST
        value: localhost
      - key: CHROMA_DB_PATH
        value: /opt/render/project/src/chroma_data
    healthCheckPath: /health/enhanced
    autoDeploy: true 